name: 'setup-conda'
description: 'Action to install miniconda and environments for SeuratIntegrate'
author: Florian Specque (@fspecque)

runs:
  using: "composite"
  steps:
      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: ""

      - name: Setup envs
        run: |
          conda create -n umap_0.5.4 umap-learn=0.5.4 -c conda-forge -y
          conda create -n SeuratIntegrate_bbknn python scipy scanpy bbknn -c conda-forge -c bioconda -y
          conda activate SeuratIntegrate_bbknn
          pip install bbknn
          conda deactivate
          conda create -n SeuratIntegrate_scanorama python scanorama scipy -c conda-forge -c bioconda -y
          conda create -n SeuratIntegrate_scvi-tools python=3.12 pip -c conda-forge
          conda activate  SeuratIntegrate_scvi-tools
          pip install jax
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install scvi-tools scanpy
          conda deactivate
        shell: bash -l {0}
        working-directory: ${{ inputs.working-directory }}

      - name: Save conda envs
        run: |
          library(SeuratIntegrate)
          print(getCache())

          integration_methods <- c("bbknn", "scanorama", "scvi")#, "trvae")
          for (method in integration_methods) {
            UpdateEnvCache(method = method)
          }
          print(getCache())
        shell: Rscript {0}
        working-directory: ${{ inputs.working-directory }}
